### ISSUE TITLE
Missing trained model file

### ISSUE THREAD

**Issue by Ayush022005** [Pawan-Kumar-J/First-Response#1]
You have not included or given link of weights file please provide wieghts file

**Comment by NaqibAhmed** [comment]
We've addressed the issue by providing a [download link](https://drive.google.com/file/d/1Vb9Ly6KxAbhdqIU1XJLbd9SPMPNdMY7k/view?usp=sharing) for the weights in the README.md file. Kindly take a moment to read through the updated README, which now includes the necessary information. Your input has helped us improve our project, and we sincerely appreciate your contribution to its development.

If you have any further questions or suggestions, please feel free to let us know. We value your involvement in our project.
